version: '3.3'

services:
  mongo:
    image: 'mongo'
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongovol:/data/db
  tweets:
    image: 'lorenzovigo/twitter-code'
    container_name: tweets
volumes:
  mongovol:
    driver: local
